#!/bin/bash 
cd /home/milnes/APASVERUS/APAS-AI/apas-ai

git mv src/ArraySeqEph.rs src/ArraySeqStEph.rs
git mv src/ArraySeqEphChap18.rs src/ArraySeqStEphChap18.rs
git mv src/ArraySeqEphChap19.rs src/ArraySeqStEphChap19.rs
git mv src/ArraySeqPer.rs src/ArraySeqStPer.rs
git mv src/ArraySeqPerChap18.rs src/ArraySeqStPerChap18.rs
git mv src/ArraySeqPerChap19.rs src/ArraySeqStPerChap19.rs
git mv src/AVLTreeSeqEph.rs src/AVLTreeSeqStEph.rs
git mv src/AVLTreeSeqEphChap18.rs src/AVLTreeSeqStEphChap18.rs
git mv src/AVLTreeSeqEphChap19.rs src/AVLTreeSeqStEphChap19.rs
git mv src/AVLTreeSeqPer.rs src/AVLTreeSeqStPer.rs
git mv src/AVLTreeSeqPerChap18.rs src/AVLTreeSeqStPerChap18.rs
git mv src/AVLTreeSeqPerChap19.rs src/AVLTreeSeqStPerChap19.rs
git mv src/DirGraphEphChap6_1.rs src/DirGraphStEphChap6_1.rs
git mv src/UnDirGraphEphChap6_1.rs src/UnDirGraphStEphChap6_1.rs
git mv src/MappingEphChap5_5.rs src/MappingStEphChap5_5.rs
git mv src/RelationEphChap5_2.rs src/RelationStEphChap5_2.rs
git mv src/SetEphChap5_1.rs src/SetStEphChap5_1.rs
git mv src/LinkedListEph.rs src/LinkedListStEph.rs
git mv src/LinkedListEphChap18.rs src/LinkedListStEphChap18.rs
git mv src/LinkedListEphChap19.rs src/LinkedListStEphChap19.rs
git mv src/LinkedListPer.rs src/LinkedListStPer.rs
git mv src/LinkedListPerChap18.rs src/LinkedListStPerChap18.rs
git mv src/LinkedListPerChap19.rs src/LinkedListStPerChap19.rs
git mv benches/BenchArraySeqEph.rs benches/BenchArraySeqStEph.rs
git mv benches/BenchArraySeqEphChap18.rs benches/BenchArraySeqStEphChap18.rs
git mv benches/BenchArraySeqEphChap19.rs benches/BenchArraySeqStEphChap19.rs
git mv benches/BenchArraySeqPer.rs benches/BenchArraySeqStPer.rs
git mv benches/BenchArraySeqPerChap18.rs benches/BenchArraySeqStPerChap18.rs
git mv benches/BenchArraySeqPerChap19.rs benches/BenchArraySeqStPerChap19.rs
git mv benches/BenchAVLTreeSeqEph.rs benches/BenchAVLTreeSeqStEph.rs
git mv benches/BenchAVLTreeSeqEphChap18.rs benches/BenchAVLTreeSeqStEphChap18.rs
git mv benches/BenchAVLTreeSeqEphChap19.rs benches/BenchAVLTreeSeqStEphChap19.rs
git mv benches/BenchAVLTreeSeqPer.rs benches/BenchAVLTreeSeqStPer.rs
git mv benches/BenchAVLTreeSeqPerChap18.rs benches/BenchAVLTreeSeqStPerChap18.rs
git mv benches/BenchAVLTreeSeqPerChap19.rs benches/BenchAVLTreeSeqStPerChap19.rs
git mv benches/BenchDirGraphEphChap6_1.rs benches/BenchDirGraphStEphChap6_1.rs
git mv benches/BenchLinkedListEph.rs benches/BenchLinkedListStEph.rs
git mv benches/BenchLinkedListEphChap18.rs benches/BenchLinkedListStEphChap18.rs
git mv benches/BenchLinkedListEphChap19.rs benches/BenchLinkedListStEphChap19.rs
git mv benches/BenchLinkedListPer.rs benches/BenchLinkedListStPer.rs
git mv benches/BenchLinkedListPerChap18.rs benches/BenchLinkedListStPerChap18.rs
git mv benches/BenchLinkedListPerChap19.rs benches/BenchLinkedListStPerChap19.rs
git mv benches/BenchMappingEphChap5_5.rs benches/BenchMappingStEphChap5_5.rs
git mv benches/BenchRelationEphChap5_2.rs benches/BenchRelationStEphChap5_2.rs
git mv benches/BenchUnDirGraphEphChap6_1.rs benches/BenchUnDirGraphStEphChap6_1.rs
git mv tests/09_TestArraySeqPer.rs tests/09_TestArraySeqStPer.rs
git mv tests/10_TestArraySeqPerChap18.rs tests/10_TestArraySeqStPerChap18.rs
git mv tests/11_TestArraySeqPerChap19.rs tests/11_TestArraySeqStPerChap19.rs
